# 请先看 uni-chat-uts readme 上推送部分的说明
# 云函数 URL 化后的地址
unipush.url=http://xxx.yyy.zzz/push
# 下面的 category 需要根据实际申请的情况去修改，但一般都是 IM
unipush.huaweiCategory=IM
unipush.harmonyCategory=IM
unipush.vivoCategory=IM
